### ISSUE TITLE
Add a prompt / text field function to .rpy scripts

### ISSUE THREAD

**Issue by vasekhodina** [liana-p/narrat#15]
Would it be possible to create an API function that would spawn a text field and a button in the text area on the right? Player would input a string there and press the confirmation button. The string would be saved in a variable and the author could work with it further. This would enable the authors to ask for names, money amount etc.

**Comment by nialna** [comment]
It should be possible, I was thinking of doing that. I'll look into adding it

**Comment by liana-p** [comment]
This has been done now [see docs](https://docs.get-narrat.com/functions-documentation/text-field)
